// const FETCH_USERS_REQUESTED = 'FETCH_USERS_REQUESTED';
// const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
// const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';
const FETCH_USERS = 'FETCH_USERS';
const TOGGLE_CHECKED_USER = 'TOGGLE_CHECKED_USER';

export {FETCH_USERS, TOGGLE_CHECKED_USER};